# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UniW46xQLsdP5SfgPIXobVo6xEZrJXBQ
"""

# --- SIDEBAR INPUTS ---
with st.sidebar:
    st.header("1. Log Contribution")
    year = st.number_input("Year", value=2025)
    salary = st.number_input("Annual Salary (£)", min_value=0.0, step=1000.0)
    accrual_denom = st.selectbox("Accrual Rate (1/x)", [49, 57, 60], index=0)
    cpi = st.slider("Inflation Revaluation (%)", -2.0, 10.0, 2.0) / 100

    if st.button("Secure Year in Blockchain"):
        accrual_rate = 1 / accrual_denom
        new_record = PensionRecord(year, salary, accrual_rate, cpi)
        prev_hash = st.session_state.chain[-1].hash_block()
        new_block = Block(len(st.session_state.chain), new_record, prev_hash)
        st.session_state.chain.append(new_block)
        st.success(f"Year {year} locked!")

    st.divider()

    # --- NEW: RETIREMENT SETTINGS SPACE ---
    st.header("2. Retirement Settings")
    npa = st.number_input("Normal Pension Age (NPA)", value=67, min_value=50)
    retire_age = st.number_input("Planned Retirement Age", value=67, min_value=50)
    reduction_rate = st.number_input("Annual Reduction % (if early)", value=4.0, step=0.5) / 100

# --- CALCULATIONS ---
total_pension_raw = sum(b.record.calculate_unit() for b in st.session_state.chain[1:])

# Calculate Adjustment
if retire_age < npa:
    years_early = npa - retire_age
    total_reduction = years_early * reduction_rate
    final_pension = total_pension_raw * (1 - total_reduction)
    status_msg = f"⚠️ Early Retirement: {total_reduction:.0%} total reduction applied."
elif retire_age > npa:
    # Some schemes give an increase for late retirement, but we'll cap at 100% for now
    final_pension = total_pension_raw
    status_msg = "✅ Late Retirement: 100% of accrued pension awarded."
else:
    final_pension = total_pension_raw
    status_msg = "✅ Retirement at NPA: 100% of accrued pension awarded."

# --- DISPLAY SUMMARY ---
st.subheader("Financial Projection")
c1, c2, c3 = st.columns(3)
c1.metric("Accrued Base Pension", f"£{total_pension_raw:,.2f}")
c2.metric("Adjustment Factor", f"{(final_pension/max(total_pension_raw,1)):.0%}")
c3.metric("Final Annual Payout", f"£{final_pension:,.2f}")

st.info(status_msg)